import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <a className={styles.navItems} href="/">
            Home
          </a>
          <a className={styles.navItems} href="/events">
            Events
          </a>
          <a className={styles.navItems} href="/AboutUsPage">
            About Us
          </a>
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((event) => {
          return (
            <a key={event.id} href={`/events/${event.id}`}>
              <p>hello</p>
              <Image
                width={200}
                height={100}
                src={event.image}
                alt={event.title}
              />
              <h2>{event.title}</h2>
              <p>{event.description}</p>
            </a>
          );
        })}
        {/* <a href="/events/london">
          <h2>Events in London</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cum
            delectus error voluptatem molestiae cumque magni nobis quasi ullam
            eveniet asperiores optio illum, omnis voluptate ratione, quidem hic
            ipsum laboriosam debitis.
          </p>
        </a>
        <a href="/events/sanfrancisco">
          <h2>Events in San Francisco</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cum
            delectus error voluptatem molestiae cumque magni nobis quasi ullam
            eveniet asperiores optio illum, omnis voluptate ratione, quidem hic
            ipsum laboriosam debitis.
          </p>
        </a>
        <a href="/events/barcelona">
          <h2>Events in Barcelona</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cum
            delectus error voluptatem molestiae cumque magni nobis quasi ullam
            eveniet asperiores optio illum, omnis voluptate ratione, quidem hic
            ipsum laboriosam debitis.
          </p>
        </a> */}
      </main>
      <footer className={styles.footer}>
        <p> © 2023 Events Project</p>
      </footer>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}
