import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <a className={styles.navItems} href="/">Events</a>
          <a className={styles.navItems} href="/events">Home</a>
          <a className={styles.navItems} href="/AboutUsPage">About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <div>
          <h2>Events in London</h2>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cum delectus error voluptatem molestiae cumque magni nobis quasi ullam eveniet asperiores optio illum, omnis voluptate ratione, quidem hic ipsum laboriosam debitis.</p>
        </div>
      </main>
      <footer className={styles.footer}>
        <p> © 2023 Events Project</p>
      </footer>
    </>
  )
}
